# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1Ugex0HfObJUNaLBnySBu5Rb7IuN-yy
"""

print("Write down the names of processes as p0,p1 .... seperated by space")
list_of_process=list(map(str,input().split()))
print("Process Names",list_of_process)
print("Write down the values of Arrival time for  processes  .... seperated by space")
arrival_time=list(map(float,input().split()))
print("Arrival Time",arrival_time)
print("Write down the values of Burst time for  processes  .... seperated by space")
burst_time=list(map(float,input().split()))
print("Burst Time",burst_time)
dict_=list(zip(list_of_process,arrival_time,burst_time))
print(dict_)
l=len(dict_)
#  Sorting the Processes
for i in range(0,l):
    for j in range(0,l-i-1):
        if(dict_[j][1]>dict_[j+1][1]):
            temp=dict_[j]
            dict_[j]=dict_[j+1]
            dict_[j+1]=temp
print("Sorted Processes",dict_)

# Calculation  of completion time
completion_time=[]
completion_time1=[]
k=0
for i,j,k in dict_:
  # print(k)
  completion_time1.append(k) 
completion_time.append(completion_time1[0])
for i in range(0,len(completion_time1)-1):
  if(i==0):
    k=completion_time1[i]+completion_time1[i+1]
    completion_time.append(k)
  else:
    k=completion_time1[i+1]+k
    completion_time.append(k)
  

  arrival_time1=[]
  Burst_time1=[]
  for i,j,k in dict_:
    arrival_time1.append(j)
    Burst_time1.append(k)
  print('Completion time',completion_time)



#Calculation of turn-around-time

turn_around_time=[]
zip_=zip(completion_time,arrival_time1)
for i,j in zip_:
   turn_around_time.append(i-j)
print('Turn-Around-Time',turn_around_time)



#Calculation of Waiting Time

Waiting_time=[]
zip_=zip(turn_around_time,Burst_time1)
for i,j in zip_:
  Waiting_time.append(i-j)
print('Waiting-Time',Waiting_time)



# Calculation of Avg Waiting Time
sum_=sum(Waiting_time)
l1=len(Waiting_time)
Avg_Wait_time=sum_/l1
print("Avg Waiting Time" , Avg_Wait_time)